version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      # - npm run test
  post_build:
    commands:
      - echo Build completed on `date`

# cache:
#   paths:
#     - 'node_modules/**/*'

artifacts:
  files:
    - '**/*'
  name: test-lin-$(date +%Y-%m-%d)
# artifacts:
#   files:
#     - dist/**/*
#     - package.json
#     - package-lock.json
#     - node_modules/**/*
#   name: test-lin-$(date +%Y-%m-%d)

